services:
  db:
    image: postgres:16-alpine
    container_name: history_master_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - history_master_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - history_master_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: history_master_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      HISTORY_MASTER_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      BUNDLE_PATH: /usr/local/bundle
    volumes:
      - .:/rails  # Montaje del c√≥digo para desarrollo
      - history_master_bundle_cache:/usr/local/bundle
      - history_master_storage_data:/rails/storage
      - history_master_log_data:/rails/log
    ports:
      - "3000:3000"
    networks:
      - history_master_network
    restart: unless-stopped
    command: /bin/bash -c "./bin/rails db:prepare && ./bin/rails server -b 0.0.0.0"

volumes:
  history_master_postgres_data:
    driver: local
  history_master_bundle_cache:
    driver: local
  history_master_storage_data:
    driver: local
  history_master_log_data:
    driver: local

networks:
  history_master_network:
    driver: bridge

